CREATE TABLE [dbo].[B_ForeignExchange](
	[TTNo] [varchar](50) NOT NULL,
	[CustomerName] [nvarchar](150) NOT NULL,
	[CustomerAddress] [nvarchar](150) NOT NULL,
	[CustomerPassportNo] [varchar](50) NOT NULL,
	[CustomerPassportDateOfIssue] [varchar](10) NULL,
	[CustomerPassportPlaceOfIssue] [varchar](50) NULL,
	[CustomerPhoneNo] [varchar](50) NULL,
	[TellerID] [varchar](50) NOT NULL,
	[DebitCurrency] [varchar](3) NOT NULL,
	[DebitAccount] [varchar](50) NULL,
	[DebitAmtLCY] [decimal](18, 4) NULL,
	[DebitAmtFCY] [decimal](18, 4) NULL,
	[CurrencyPaid] [varchar](3) NOT NULL,
	[CrTellerID] [nchar](10) NULL,
	[CreditAccount] [varchar](50) NULL,
	[DealRate] [decimal](18, 4) NULL,
	[AmountPaid] [decimal](18, 4) NULL,
	[Narrative] [nvarchar](500) NULL,
	[Status] [varchar](3) NULL,
	[UserCreate] [varchar](50) NOT NULL,
	[DateTimeCreate] [datetime] NOT NULL,
	[UserApprove] [varchar](50) NULL,
	[DateTimeApprove] [datetime] NULL
) ON [PRIMARY]