//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPeriods
    {
        public AccountPeriods()
        {
            this.Shifts = new HashSet<Shifts>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime BeginPeriod { get; set; }
        public System.DateTime EndPeriod { get; set; }
        public int WorkingDay { get; set; }
        public int AvailableSlot { get; set; }
        public bool IsBlocked { get; set; }
        public bool IsEnabled { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Shifts> Shifts { get; set; }
    }
}
