//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankProject.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCASH_REPAYMENT
    {
        public string ID { get; set; }
        public string Status { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Currency { get; set; }
        public string CustomerAccountID { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<decimal> NewBalanceAmount { get; set; }
        public string TellerID { get; set; }
        public string CurrencyDeposited { get; set; }
        public string CashAccountID { get; set; }
        public string CashAccountName { get; set; }
        public Nullable<decimal> AmountDeposited { get; set; }
        public Nullable<decimal> NextTranCom { get; set; }
        public Nullable<decimal> DealRate { get; set; }
        public string WaiveCharges { get; set; }
        public string Narrative { get; set; }
        public string Narrative2 { get; set; }
        public Nullable<decimal> PrintLnNoOfPS { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ActiveFlag { get; set; }
    }
}
